id: rce-automation

info:
  name: RCE Vulnerability Check
  author: rix4uni
  severity: critical
  description: Checks for Remote Code Excution vulnerabilities
  tags: rce

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    payloads:
      reflection:
        - "ipconfig"
        - "id"

    fuzzing:
      - part: query
        type: replace
        mode: multiple
        fuzz:
          - "{{reflection}}"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "uid="
          - "gid="
          - "Windows IP Configuration"

      - type: status
        status:
          - 200