id: js-leaks-automation

info:
  name: LFI
  author: rix4uni
  severity: Medium
  reference:
    - https://hackerone.com/reports/1419213
  metadata:
    verified: true
  tags: lfi,tech

requests:
  - method: GET
    path:
      - '{{BaseURL}}'
    threads: 80

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'root'
          - 'access_key'
          - 'access_token'
          - 'accessKey'
          - 'accessToken'
          - 'api_key'
          - 'api_secret'
          - 'apikey'
          - 'app_id'
          - 'appId'
          - 'app_key'
          - 'app_secret'
          - 'application_id'
          - 'asws_secret_token'
          - 'aws_access'
          - 'aws_config'
          - 'aws_key'
          - 'aws_secret'
          - 'aws_secret_access_key'
          - 'aws_secret_key'
          - 'aws_token'
          - 'amazon_aws_access_key_id'
          - 'AMAZON_AWS_ACCESS_KEY_ID'
          - 'bucket_password'
          - 'client_secret'
          - 'connectionstring'
          - 'consumer_secret'
          - 'credentials'
          - 'db_password'
          - 'db_server'
          - 'db_username'
          - 'dbpasswd'
          - 'dbpassword'
          - 'dbuser'
          - 'django_password'
          - 'email_host_password'
          - 'facebook_app_secret'
          - 'facebook_secret'
          - 'fb_app_secret'
          - 'fb_secret'
          - 'FIREBASE_API'
          - 'FirebaseAuth'
          - 'firebaseConfig'
          - 'google_id'
          - 'google_oauth'
          - 'google_oauth_client_id'
          - 'google_oauth_client_secret'
          - 'google_oauth_secret'
          - 'google_secret'
          - 'google_server_key'
          - 'google_api'
          - 'google_captcha'
          - 'gsecr'
          - 'GITHUB_ACCESS_TOKEN'
          - 'github_access_token'
          - 'heroku_api_key'
          - 'heroku_key'
          - 'heroku_oauth'
          - 'heroku_oauth_secret'
          - 'heroku_oauth_token'
          - 'heroku_secret'
          - 'heroku_secret_token'
          - 'jwt_secret'
          - 'jwt_token'
          - 'jwt_secret_token'
          - 'keyPassword'
          - 'mailgun_key'
          - 'mailgun_secret'
          - 'mysql_password'
          - 'oauth_key'
          - 'oauth_token'
          - 'oauth2_secret'
          - 'password'
          - 'paypal_identity_token'
          - 'paypal_sandbox'
          - 'paypal_secret'
          - 'paypal_token'
          - 'postgres_password'
          - 'private'
          - 'private_key'
          - 'redis_password'
          - 'root_password'
          - 'sa_password'
          - 'secret'
          - 'site_key'
          - 'secret_access_key'
          - 'secret_bearer'
          - 'secret_key'
          - 'secret_token'
          - 'secretKey'
          - 'security_credentials'
          - 'send_keys'
          - 'sf_username'
          - 'slack_channel'
          - 'slack_key'
          - 'slack_secret'
          - 'slack_token'
          - 'slack_url'
          - 'slack_webhook'
          - 'slack_webhook_url'
          - 'square_access_token'
          - 'square_apikey'
          - 'square_app'
          - 'square_app_id'
          - 'square_appid'
          - 'square_secret'
          - 'square_token'
          - 'squareSecret'
          - 'squareToken'
          - 'ssh2_auth_password'
          - 'sshkey'
          - 'storePassword'
          - 'strip_key'
          - 'strip_secret'
          - 'strip_secret_token'
          - 'strip_token'
          - 'stripe_key'
          - 'stripe_secret'
          - 'stripe_secret_token'
          - 'stripe_token'
          - 'stripSecret'
          - 'stripToken'
          - 'twitter_api_secret'
          - 'twitter_consumer_key'
          - 'twitter_consumer_secret'
          - 'twitter_key'
          - 'twitter_secret'
          - 'twitter_token'
          - 'twitterKey'
          - 'twitterSecret'
          - 'wordpress_password'
          - 'API-Key'
          - 'amazon_mws_auth_toke'
          - 'amazon_aws_url'
          - 'facebook_access_token'
          - 'authorization_basic'
          - 'authorization_bearer'
          - 'authorization_api'
          - 'mailgun_api_key'
          - 'twilio_api_key '
          - 'twilio_account_sid'
          - 'twilio_app_sid'
          - 'paypal_braintree_access_token'
          - 'square_oauth_secret'
          - 'stripe_standard_api'
          - 'stripe_restricted_api'
          - 'rsa_private_key'
          - 'ssh_dsa_private_key'
          - 'ssh_dc_private_key'
          - 'pgp_private_block'
          - 'json_web_token'
          - 'SSH_privKey'
          - 'AWS_ACCESS_KEY_ID'
          - 'AWS_SECRET_ACCESS_KEY'
          - 'AMAZON_AWS_SECRET_ACCESS_KEY'
          - 'ALGOLIA_API_KEY'
          - 'AZURE_CLIENT_ID'
          - 'AZURE_CLIENT_SECRET'
          - 'AZURE_USERNAME'
          - 'AZURE_PASSWORD'
          - 'MSI_ENDPOINT'
          - 'MSI_SECRET'
          - 'binance_api'
          - 'binance_secret'
          - 'BITTREX_API_KEY'
          - 'BITTREX_API_SECRET'
          - 'CF_PASSWORD'
          - 'CF_USERNAME'
          - 'CODECLIMATE_REPO_TOKEN'
          - 'COVERALLS_REPO_TOKEN'
          - 'CIRCLE_TOKEN'
          - 'DIGITALOCEAN_ACCESS_TOKEN'
          - 'DOCKER_EMAIL'
          - 'DOCKER_PASSWORD'
          - 'DOCKER_USERNAME'
          - 'DOCKERHUB_PASSWORD'
          - 'FACEBOOK_APP_ID'
          - 'FACEBOOK_APP_SECRET'
          - 'FACEBOOK_ACCESS_TOKEN'
          - 'FIREBASE_TOKEN'
          - 'FIREBASE_API_TOKEN'
          - 'FOSSA_API_KEY'
          - 'GH_TOKEN'
          - 'GH_ENTERPRISE_TOKEN'
          - 'CI_DEPLOY_PASSWORD'
          - 'CI_DEPLOY_USER'
          - 'GOOGLE_APPLICATION_CREDENTIALS'
          - 'GOOGLE_API_KEY'
          - 'GITLAB_USER_LOGIN'
          - 'CI_JOB_JWT'
          - 'CI_JOB_JWT_V2'
          - 'CI_JOB_TOKEN'
          - 'HEROKU_API_KEY'
          - 'HEROKU_API_USER'
          - 'MAILGUN_API_KEY'
          - 'MCLI_PRIVATE_API_KEY'
          - 'MCLI_PUBLIC_API_KEY'
          - 'NGROK_TOKEN'
          - 'NGROK_AUTH_TOKEN'
          - 'NPM_AUTH_TOKEN'
          - 'OKTA_CLIENT_ORGURL'
          - 'OKTA_CLIENT_TOKEN'
          - 'OKTA_OAUTH2_CLIENTSECRET'
          - 'OKTA_OAUTH2_CLIENTID'
          - 'OKTA_AUTHN_GROUPID'
          - 'OS_USERNAME'
          - 'OS_PASSWORD'
          - 'PERCY_TOKEN'
          - 'POSTGRES_PASSWORD'
          - 'SAUCE_ACCESS_KEY'
          - 'SAUCE_USERNAME'
          - 'SENTRY_AUTH_TOKEN'
          - 'SLACK_TOKEN'
          - 'STRIPE_API_KEY'
          - 'STRIPE_DEVICE_NAME'
          - 'SURGE_TOKEN'
          - 'SURGE_LOGIN'
          - 'TWILIO_ACCOUNT_SID'
          - 'CONSUMER_KEY'
          - 'CONSUMER_SECRET'
          - 'TRAVIS_SUDO'
          - 'TRAVIS_OS_NAME'
          - 'TRAVIS_SECURE_ENV_VARS'
          - 'TELEGRAM_BOT_TOKEN'
          - 'VAULT_TOKEN'
          - 'VAULT_CLIENT_KEY'
          - 'TOKEN'
          - 'VULTR_ACCESS'
          - 'VULTR_SECRET'
          - 'ConsumerKey'
          - 'ConsumerSecret'
          - 'DB_USERNAME'
          - 'HOMEBREW_GITHUB_API_TOKEN'
          - 'JEKYLL_GITHUB_TOKEN'
          - 'PT_TOKEN'
          - 'SESSION_TOKEN'
          - 'SF_USERNAME'
          - 'SLACK_BOT_TOKEN'
          - 'access-token'
          - 'access_token_secret'
          - 'accesstoken'
          - 'admin'
          - 'api-key'
          - 'api_secret_key'
          - 'api_token'
          - 'auth_token'
          - 'authkey'
          - 'authorization'
          - 'authorization_key'
          - 'authorization_token'
          - 'authtoken'
          - 'aws_access_key_id'
          - 'bearer'
          - 'bot_access_token'
          - 'bucket'
          - 'client-secret'
          - 'client_id'
          - 'client_key'
          - 'clientsecret'
          - 'consumer_key'
          - 'email'
          - 'encryption-key'
          - 'encryption_key'
          - 'encryptionkey'
          - 'id_dsa'
          - 'irc_pass'
          - 'private-key'
          - 'privatekey'
          - 'secret-key'
          - 'secretkey'
          - 'session_key'
          - 'session_secret'
          - 'slack_api_token'
          - 'slack_secret_token'
          - 'ssh-key'
          - 'ssh_key'
          - 'token'
          - 'username'
          - 'xoxa-2'
          - 'xoxr'
          - 'awsAccessKey'
          - 'awsSecretKey'
          - 'aviaryApiKey'
          - 'youtubeApiKey'
          - 'Akismet-API'
          - 'akismet-api'
          - 'akismet-api-key'
