id: netlify-detect

info:
  name: Netlify Server Detect
  author: rix4uni
  severity: info
  description: description
  reference:
    - https://
  tags: netlify,detect,technologies

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - 'Server: Netlify'

      - type: status
        status:
          - 200